site_name: Bahalla's Learning Journey
site_url: https://bahalla.github.io/learning-documentation/
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
nav:
  - Home: index.md
  - Kafka: kafka.md
  - Kubernetes: kubernetes.md

markdown_extensions:
  - admonition           # <â€“ needed for !!! info/warning/success
  - pymdownx.details     # collapsible details
  - pymdownx.superfences # fenced blocks inside admonitions
  - pymdownx.emoji       # if you want the emoji icons to look nicer